apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: runners
spec:
  template:
    metadata:
      labels:
        workload: runner
    spec:
      taints:
        - key: runner
          value: "true"
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m", "c", "t"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: runners
      terminationGracePeriod: {{ .Values.nodeGracePeriodSeconds }}s
      expireAfter: 720h
  limits:
    cpu: "{{ .Values.cpuLimit }}"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: {{ .Values.consolidateAfterSeconds }}s
