version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps)"
    groups:
      actions-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/modules/eks"
      - "/modules/vpc"
      - "/modules/secrets"
      - "/modules/secrets-store-csi"
      - "/modules/runner-scale-set"
      - "/s3-backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    groups:
      aws-providers:
        patterns: ["hashicorp/aws*"]
      minor-patch:
        update-types: [minor, patch]
        exclude-patterns: ["hashicorp/aws*"]
